workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: <App Store Connect API key name>
    environment:
      vars:
        APP_STORE_APPLE_ID: 1555555551
    scripts:
      - name: Flutter build ipa
        script: | 
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          flutter build ipa --release \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
environment:
  groups:
    -firebase_credentials

scripts:
  - name: Publish to Firebase Hosting
    script: | 
      firebase deploy --token "1//0hqpWLB4VMq3eCgYIARAAGBESNwF-L9IrA0Z6Uv98TRajdRyifgSiecwUAZI2XEQaYrZ-sRptszwbiXRbQDxe5WvYg34RD6JP-6I"

publishing: 
      email:
        recipients:
          - echo.alexandre@gmail.com
        notify:
          success: true
          failure: false