// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhS4cw23-5hqxeqt7OUYrFT6ZEpXBzZaw',
    appId: '1:773512884357:web:464fc44332fa83a1c679ec',
    messagingSenderId: '773512884357',
    projectId: 'eaecontrol',
    authDomain: 'eaecontrol.firebaseapp.com',
    storageBucket: 'eaecontrol.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbyu9enDMHhLhn3sR2NFDb3s4o54mIrE',
    appId: '1:773512884357:android:51a9fa90522f2d63c679ec',
    messagingSenderId: '773512884357',
    projectId: 'eaecontrol',
    storageBucket: 'eaecontrol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOcGkuZHWCk1HRQlNuDtYerbgYOE-Chf0',
    appId: '1:773512884357:ios:73a5a905fe98cbe3c679ec',
    messagingSenderId: '773512884357',
    projectId: 'eaecontrol',
    storageBucket: 'eaecontrol.appspot.com',
    iosBundleId: 'com.example.eaecontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOcGkuZHWCk1HRQlNuDtYerbgYOE-Chf0',
    appId: '1:773512884357:ios:73a5a905fe98cbe3c679ec',
    messagingSenderId: '773512884357',
    projectId: 'eaecontrol',
    storageBucket: 'eaecontrol.appspot.com',
    iosBundleId: 'com.example.eaecontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhS4cw23-5hqxeqt7OUYrFT6ZEpXBzZaw',
    appId: '1:773512884357:web:96b32086d7a4d6fdc679ec',
    messagingSenderId: '773512884357',
    projectId: 'eaecontrol',
    authDomain: 'eaecontrol.firebaseapp.com',
    storageBucket: 'eaecontrol.appspot.com',
  );

}